### ISSUE TITLE
Difficulty in running

### ISSUE THREAD

**Issue by laopidu** [zhangce01/HiKER-SGG#4]

**Comment by zhangce01** [comment]
The original issue is:
"_Hello, thanks for your sharing and specific instructions.
But due to my technical issues, i got stuck with the step of running.I don't know if you have the .py files instead of .ipynb that adapt to train and evaluate. I would be extremely grateful if there are._"

Hi,

Thank you for the interest in this work. We follow previous methods to use Jupyter notebooks for better debugging and result visualization. You can simply convert .ipynb file to .py scripts by: `jupyter nbconvert --to script [YOUR_NOTEBOOK].ipynb`.

Please let me know if you have any other questions.

**Comment by laopidu** [comment]
God! Thank you! I closed that issue precisely because  it's  too simple.And i did indeed perform this "nbvonvert" operation.
